version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build and test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

workflows:
  sample: 
    jobs:
      - build-and-test
